services:
  # API Server
  - type: web
    name: motocross-livestream-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - fromGroup: motocross-streaming-keys
    autoDeploy: true
    healthCheckPath: /health
    
  # RTMP Streaming Server
  - type: web
    name: motocross-rtmp-server
    env: docker
    plan: free
    dockerfilePath: ./streaming/Dockerfile
    envVars:
      - key: RTMP_PORT
        value: 1935
      - key: HTTP_PORT
        value: 8080
      - key: INTERNAL_API_URL
        value: "motocross-livestream-api:8080"
      - fromGroup: motocross-streaming-keys
    autoDeploy: true
    healthCheckPath: /health

envVarGroups:
  - name: motocross-streaming-keys
    envVars:
      - key: API_KEY
        sync: false
      - key: STORAGE_BUCKET
        sync: false
