services:
  # API Server
  - type: web
    name: motocross-livestream-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: RTMP_SERVER_URL
        value: https://motocross-rtmp-server.onrender.com
      - fromGroup: motocross-streaming-keys
    autoDeploy: true
    healthCheckPath: /health

  # RTMP Server
  - type: web
    name: motocross-rtmp-server
    env: docker
    plan: free
    dockerfilePath: Streaming/Dockerfile
    buildCommand: cd Streaming && docker build -t motocross-rtmp .
    envVars:
      - key: RTMP_PORT
        value: 1935
      - key: HTTP_PORT
        value: 8080
      - key: RTMP_AUTH_URL
        value: https://motocross-livestream-api.onrender.com
      - fromGroup: motocross-streaming-keys
    autoDeploy: true
    healthCheckPath: /health

envVarGroups:
  - name: motocross-streaming-keys
    envVars:
      - key: API_KEY
        sync: false
      - key: STORAGE_BUCKET
        sync: false
      - key: HLS_BASE_URL
        value: https://motocross-rtmp-server.onrender.com/hls
